### PR TITLE
#8: Fixed wrong metrics

### LINKED ISSUE #8: Metrics have wrong unit
While Exasol stores the values in MiB, GiB and MiB/s Cloudwatch uses MB, GB, and MB/s.

Currently, the CloudtWach adapter reports the unchanged value under the wrong unit.

## Fix:

Convert data during transfer

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #8

### CODE REVIEW

File: src/main/java/com/exasol/cloudwatch/ExasolToCloudwatchMetricDatumConverter.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
+package com.exasol.cloudwatch;
+
+import com.exasol.errorreporting.ExaError;
+
+import software.amazon.awssdk.services.cloudwatch.model.*;
+
+public class ExasolToCloudwatchMetricDatumConverter {
```
Comment (morazow) [inline src/main/java/com/exasol/cloudwatch/ExasolToCloudwatchMetricDatumConverter.java:7]: Missing javadoc. Add also short description about expected unit in cloudwatch.

**Review by morazow — APPROVED** [review]

**Review by morazow — APPROVED** [review]
