### PR TITLE
#82: Remove maven.exasol.com

### LINKED ISSUE #82: Project uses outdated repo maven.exasol.com
```
Error:  Failed to execute goal on project cloudwatch-adapter: Could not resolve dependencies for project com.exasol:cloudwatch-adapter:jar:1.0.5: Failed to collect dependencies at com.exasol:exasol-jdbc:jar:7.1.11: Failed to read artifact descriptor for com.exasol:exasol-jdbc:jar:7.1.11: Could not transfer artifact com.exasol:exasol-jdbc:pom:7.1.11 from/to maven.exasol.com (https://maven.exasol.com/artifactory/exasol-releases): transfer failed for https://maven.exasol.com/artifactory/exasol-releases/com/exasol/exasol-jdbc/7.1.11/exasol-jdbc-7.1.11.pom: Unknown host maven.exasol.com -> [Help 1]
```

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #82

### CODE REVIEW

File: src/test/java/com/exasol/cloudwatch/TestConstants.java [hunk 1]
```diff
@@ -1,6 +1,6 @@
 package com.exasol.cloudwatch;
 
 public class TestConstants {
-    public static final String EXASOL_DOCKER_DB_VERSION = "7.1.12";
-    public static final String LOCAL_STACK_IMAGE = "localstack/localstack:1.0.3";
+    public static final String EXASOL_DOCKER_DB_VERSION = "7.1.17";
```
Comment (morazow) [inline src/test/java/com/exasol/cloudwatch/TestConstants.java:4]: Maybe update it to version `7.1.18`?

**Review by morazow — APPROVED** [review]
