### PR TITLE
#57 Add support for Backup events

### LINKED ISSUE #57: Add support for reporting backup events
For administrators it would be helpful to create CloudWatch alerts that indicate if an Exasol backup succeeded or failed.

For that we can add a Metric based on events in the [`EXA_SYSTEM_EVENTS`](https://docs.exasol.com/saas/sql_references/system_tables/statistical/exa_system_events.htm) table. We need to report the following events:

* `BACKUP_START`
* `BACKUP_END`
* `BACKUP_ABORTED`

The user must be able to configure which events should be used.

### LINKED ISSUE #59: Update log4j library to 2.17.1 version

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #57
Closes #59

### CODE REVIEW

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+import java.time.temporal.ChronoUnit;
+import java.util.*;
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import com.exasol.errorreporting.ExaError;
+
+/**
+ * This {@link ExasolEventMetricsReader} reads the duration of the finished within the last minute.
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:17]: `of the finished ` what?

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+                        timestamp, backupDurationSeconds, clusterName));
+            }
+        }
+        return result;
+    }
+
+    private String buildQuery() {
+        return "with intermediate as ( " //
+                + "    select s.cluster_name, s.measure_time, s.event_type, " //
+                + "        lead(event_type) over (partition by cluster_name order by measure_time) end_event, " //
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:75]:
```suggestion
                + "        lead(event_type, 1) over (partition by cluster_name order by measure_time) next_event_event, " //
```

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+                + "        lead(measure_time) over (partition by cluster_name order by measure_time) end_time " //
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:76]:
```suggestion
                + "        lead(measure_time, 1) over (partition by cluster_name order by measure_time) next_event_time " //
```

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java (hunk 2 above)
Comment (jakobbraun) [reply src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:75]: It would help to read if we can extract a var / function here

For example:
getEventTypeOfNextEventOnSameCluster

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+                final double backupDurationSeconds = resultSet.getDouble("backup_duration_sec");
+                result.add(new ExasolMetricDatum(ExasolBackupDurationReaderFactory.METRIC_NAME, ExasolUnit.SECONDS,
+                        timestamp, backupDurationSeconds, clusterName));
+            }
+        }
+        return result;
+    }
+
+    private String buildQuery() {
+        return "with intermediate as ( " //
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:73]: add Javadoc that describes the columns of intermediate

Comment (jakobbraun) [reply src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:73]: rename. Maybe to eventsWithNextEvent

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReaderFactory.java [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+import java.sql.Connection;
+import java.util.Optional;
+import java.util.Set;
+
+/**
+ * Factory for {@link ExasolBackupDurationReader}.
+ */
+class ExasolBackupDurationReaderFactory implements ExasolMetricReaderFactory {
+
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReaderFactory.java:11]:
```suggestion
```

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolEventMetricsReader.java [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+
+    @Override
+    public List<ExasolMetricDatum> readMetrics(final Collection<String> metricsNames, final Instant ofMinute) {
+        final List<ExasolEvent> metrics = metricsNames.stream().map(ExasolEvent::forName).collect(Collectors.toList());
+        if (metrics.isEmpty()) {
+            return emptyList();
+        }
+        final Instant start = ofMinute.truncatedTo(ChronoUnit.MINUTES);
+        final Instant end = start.plus(Duration.ofMinutes(1));
+
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolEventMetricsReader.java:44]:
```suggestion
```

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolStatisticsTableEventsMetricReader.java [hunk 7]
```diff
@@ -14,15 +15,23 @@
  */
 class ExasolStatisticsTableEventsMetricReader extends AbstractExasolStatisticsTableMetricReader {
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolStatisticsTableEventsMetricReader.java:17]:
```suggestion
```

**Review by jakobbraun — CHANGES_REQUESTED** [review]

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java (hunk 4 above)
Comment (kaklakariada) [reply src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java]: ✅

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java (hunk 1 above)
Comment (kaklakariada) [reply src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java]: ✅

File: src/main/java/com/exasol/cloudwatch/CloudWatchAdapter.java [hunk 8]
```diff
@@ -56,6 +56,12 @@ public CloudWatchAdapter() {
 
     @Override
     public Void handleRequest(final ScheduledEvent event, final Context context) {
+        if ((event == null) || (event.getTime() == null)) {
+            throw new IllegalArgumentException(ExaError.messageBuilder("W-CWA-32")
```
[the remark this answers is not in the document]
Comment (kaklakariada) [reply src/main/java/com/exasol/cloudwatch/CloudWatchAdapter.java]: ✅

File: src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java [hunk 9]
```diff
@@ -69,23 +69,48 @@
...
+     * <li>{@code utc_end_time}: UTC timestamp when the backup finished</li>
+     * <li>{@code backup_duration_sec}: Duration of the backup in seconds</li>
+     * </ol>
+     * The query has two arguments:
+     * <ol>
+     * <li>Minimum timestamp of the BACKUP_END or BACKUP_ABORTED event (included)</li>
+     * <li>Maximum timestamp of the BACKUP_END or BACKUP_ABORTED event (excluded)</li>
+     * </ol>
+     *
+     * The query uses and {@code INTERMEDIATE} query {@code eventsWithNextEvent} which a backup event and its following
```
Comment (jakobbraun) [inline src/main/java/com/exasol/cloudwatch/exasolmetrics/ExasolBackupDurationReader.java:85]: i don't get this sentence

**Review by jakobbraun — CHANGES_REQUESTED** [review]

**Review by jakobbraun — DISMISSED** [review]

**Review by jakobbraun — APPROVED** [review]
